#pragma once
#include <move_group_interface_client/client_behaviors/cb_move_end_effector.h>
#include <move_group_interface_client/client_behaviors/cb_move_end_effector_relative.h>
#include <move_group_interface_client/client_behaviors/cb_move_cartesian_relative.h>
#include <move_group_interface_client/client_behaviors/cb_move_joints.h>
#include <move_group_interface_client/client_behaviors/cb_move_known_state.h>
#include <move_group_interface_client/client_behaviors/cb_move_named_target.h>
#include <move_group_interface_client/client_behaviors/cb_attach_object.h>
#include <move_group_interface_client/client_behaviors/cb_detach_object.h>