name: Code Format & Quality

on:
  pull_request:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    container:
        image: ubuntu:20.04
    steps:
    - run: |
        apt-get update
        apt-get install -y clang-format-10 python-pip git
        python -m pip install pre-commit
    - uses: actions/checkout@v3
    - run: |
        pre-commit run -a
