name: Code Format & Quality

on:
  pull_request:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    container:
        image: ubuntu:20.04
    steps:
    - run: |
        apt-get update
        apt-get install -y clang-format-10
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - uses: pre-commit/action@v3.0.0
